# Generated by Django 4.1.4 on 2023-10-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
