# Generated by Django 4.2.6 on 2023-10-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first_name', max_length=30)),
                ('last_name', models.CharField(default='last', max_length=30)),
                ('email', models.EmailField(default='ab@gmail.com', max_length=50)),
                ('password', models.CharField(default='pass', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
